frontpage/urls.py
from django.urls import path

from . import views


app_name = "frontpage"
urlpatterns = [
    path("", views.index, name="frontpage"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("admin/", admin.site.urls),
    path("", include("frontpage.urls")),
]

polls/urls.py
from django.urls import path

from . import views


app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

frontpage/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

frontpage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "index.html", context={})

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Your New Django App</title>

  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Almarai:wght@800&amp;family=Nunito+Sans&amp;display=swap" />
</head>

<body>
  <div class="container">
    <div class="content">
      <img src="https://assets.codepen.io/43365/logo.svg" alt="DigitalOcean Logo" width="100" />
      <h1>Welcome to your new <a href="https://www.djangoproject.com/">Django App</a>!</h1>

      <p>
        This application is an example of how to deploy a Django Application, specifically the <a
          href="https://docs.djangoproject.com/en/3.1/intro/tutorial01/">Django Polls App</a> to DigitalOcean's App
        Platform. Check out their <a href="https://docs.djangoproject.com/en/3.1/intro/tutorial01/">documentation</a> to
        learn about the app.
      </p>

      <p>
        To finish setup, perform the following tasks:
      <ol>
        <li>Navigate to the Console tab in your app dashboard</li>
        <li>In the console, run the command <em>python manage.py migrate</em> to perform the inital database migrations
        </li>
        <li>In the console, run the command <em>python manage.py createsuperuser</em> and follow the prompt to create
          your super user</li>
      </ol>
      </p>
    </div>

    <div class="links">
      <a href="#" target="_blank" rel="noopener noreferrer"><strong>Django on App Platform Tutorial</strong>
        <span>Learn how to deploy your Django App to DigitalOcean</span>
      </a>
      <a href="https://www.digitalocean.com/docs/app-platform/languages-frameworks/python/" target="_blank"
        rel="noopener noreferrer"><strong>DigitalOcean App Platform Docs for Django</strong>
        <span>DigitalOcean's reference documentation for Django</span>
      </a>
      <a href="https://www.digitalocean.com/docs/app-platform/" target="_blank" rel="noopener noreferrer"><strong>App
          Platform Documentation</strong><span>Learn about DigitalOcean's App Platform</span></a>
      <a href="https://www.digitalocean.com/docs/droplets/how-to/" target="_blank" rel="noopener noreferrer"><strong>App
          Platform API Documentation</strong>
        <span>REST API Documentation for App Platform</span>
      </a>
    </div>
  </div>

  <div id="stripes">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    <span></span>
  </div>

  <style>
    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      padding: 50px;
      min-height: 100vh;
      position: relative;
      color: #fff;
      font-family: "Nunito Sans", sans-serif;
      font-size: 19px;
    }

    h1,
    h2,
    h3,
    h4,
    h5,
    h6 {
      font-family: "Almarai", sans-serif;
    }

    :root {
      --background: linear-gradient(150deg,
          #17acff 15%,
          #016aff 70%,
          #68a6ff 94%);
      --first: #53f;
      --second: #4553ff;
      --third: #4f40ff;
      --fourth: #25ddf5;
      --fifth: #1fa2ff;
    }

    #stripes {
      position: absolute;
      top: 0;
      left: 0;
      z-index: -1;
      width: 100%;
      height: 100vw;
      display: grid;
      background: var(--background);
      grid-template-columns: repeat(6, 1fr);
      grid-template-rows: repeat(4, 1fr);
      transform: skewY(-12deg);
      transform-origin: 0;
    }

    #stripes span {
      /* border: 1px solid #c00c00; */
    }

    #stripes span:first-child {
      grid-column: span 1;
      background: var(--first);
    }

    #stripes span:nth-child(2) {
      grid-column: span 2;
      background: var(--second);
    }

    #stripes span:nth-child(3) {
      grid-column: span 2;
      background: var(--third);
    }

    #stripes span:nth-child(4) {
      grid-column: 6;
      grid-row: 3;
      background: var(--fourth);
    }

    #stripes span:nth-child(5) {
      grid-column: span 2;
      grid-row: 4;
      background: var(--fifth);
    }

    .container {
      max-width: 800px;
      margin: 0 auto;
      padding: 50px 0;
    }

    .content {
      text-align: center;
    }

    h1 {
      font-size: 2.5rem;
    }

    h1 a {
      color: #dbf1f5;
    }

    h1 a:hover {
      color: #7decff;
    }

    p {
      margin-bottom: 50px;
    }

    li {
      text-align: left
    }

    code {
      display: inline-block;
      padding: 3px 6px;
      margin-left: 3px;
      margin-right: 3px;
      border-radius: 5px;
      font-size: 0.8rem;
      background: #1a2279;
      color: #dbf1f5;
    }

    .links {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 20px;
    }

    .links a {
      position: relative;
      display: block;
      background: rgba(255, 255, 255, 0.85);
      border-radius: 5px;
      padding: 20px;
      font-size: 1.1rem;
      text-decoration: none;
      color: #222;
      transition: 0.3s ease all;
      overflow: hidden;
    }

    .links a:before,
    .links a:after {
      font-size: 40px;
      display: block;
      position: absolute;
    }

    .links a:before {
      content: "";
      top: -80%;
      right: -150px;
      width: 250px;
      height: 250px;
      background: rgba(125, 236, 255, 0.6);
      pointer-events: none;
      transform: rotate(-25deg);
      transition: 0.4s cubic-bezier(0.34, 0.31, 0, 1.81) transform;
    }

    .links a:after {
      content: "👉";
      top: 0;
      bottom: 0;
      display: flex;
      align-items: center;
      right: 30px;
      transform: translateX(80px);
      transition: 0.3s cubic-bezier(0.34, 0.31, 0, 1.81) transform;
    }

    .links a:hover {
      background: rgba(255, 255, 255, 0.9);
      box-shadow: 5px 5px 0 rgba(0, 0, 0, 0.5);
    }

    .links a:hover:before {
      transform: rotate(-25deg) translateX(60px);
    }

    .links a:hover:after {
      transform: none;
    }

    .links a strong,
    .links a span {
      position: relative;
      z-index: 1;
    }

    .links a strong {
      font-weight: bold;
      display: block;
      margin-bottom: 5px;
    }

    .links a span {
      color: #787878;
      font-size: 0.9rem;
    }
  </style>
</body>

</html>